import type { RuleNode } from '../../model/ruleSource'

/**
 * 5 付録の骨格。
 *
 * @remarks
 * 出典: 公益財団法人日本体操協会『新体操男子規則 2025年版』84〜101ページ。
 * 各規程の末尾にある「付則」は、冊子どおり、その規程の本文の続きとして持たせている
 */
export const APPENDIX_STRUCTURE: RuleNode = {
  key: 'appendix',
  number: '5',
  page: 84,
  endPage: 100,
  children: [
    {
      key: 'appendix.judge',
      number: '1',
      page: 85,
      children: [
        { key: 'appendix.judge.purpose', number: '第1条', page: 85 },
        { key: 'appendix.judge.duties', number: '第2条', page: 85 },
        { key: 'appendix.judge.authority', number: '第3条', page: 85 },
        { key: 'appendix.judge.eligibility', number: '第4条', page: 85 },
        { key: 'appendix.judge.course', number: '第5条', page: 85 },
        { key: 'appendix.judge.briefing', number: '第6条', page: 86 },
        { key: 'appendix.judge.validity', number: '第7条', page: 86 },
        { key: 'appendix.judge.renewal', number: '第8条', page: 86 },
        { key: 'appendix.judge.suspension', number: '第9条', page: 86 },
        { key: 'appendix.judge.demotion', number: '第10条', page: 87 },
        { key: 'appendix.judge.application', number: '第11条', page: 87 },
        { key: 'appendix.judge.fee', number: '第12条', page: 87 },
        { key: 'appendix.judge.card', number: '第13条', page: 87 },
        { key: 'appendix.judge.supplementary', number: '', page: 87 },
        {
          key: 'appendix.judge.feeTable',
          number: '',
          page: 88,
          figures: ['tables/judge-application-fee'],
        },
      ],
    },
    {
      key: 'appendix.registration',
      number: '2',
      page: 89,
      children: [
        { key: 'appendix.registration.purpose', number: '第1条', page: 89 },
        { key: 'appendix.registration.memberTypes', number: '第2条', page: 89 },
        { key: 'appendix.registration.eligibility', number: '第3条', page: 89 },
        { key: 'appendix.registration.procedure', number: '第4条', page: 90 },
        { key: 'appendix.registration.dualAffiliation', number: '第5条', page: 90 },
        { key: 'appendix.registration.delegation', number: '第6条', page: 90 },
        { key: 'appendix.registration.fee', number: '第7条', page: 91 },
        {
          key: 'appendix.registration.feeTable',
          number: '',
          page: 92,
          figures: ['tables/registration-fee'],
        },
        { key: 'appendix.registration.memberCode', number: '第8条', page: 92 },
        { key: 'appendix.registration.applicationPeriod', number: '第9条', page: 92 },
        { key: 'appendix.registration.validity', number: '第10条', page: 92 },
        { key: 'appendix.registration.unregistered', number: '第11条', page: 92 },
        { key: 'appendix.registration.foreigners', number: '第12条', page: 93 },
        { key: 'appendix.registration.affiliation', number: '第13条', page: 93 },
        { key: 'appendix.registration.transferNotice', number: '第14条', page: 93 },
        { key: 'appendix.registration.transferRestriction', number: '第15条', page: 93 },
        { key: 'appendix.registration.participation', number: '第16条', page: 93 },
        { key: 'appendix.registration.changeNotice', number: '第17条', page: 93 },
        { key: 'appendix.registration.reviewCommittee', number: '第18条', page: 93 },
        { key: 'appendix.registration.refusal', number: '第19条', page: 94 },
        { key: 'appendix.registration.amendment', number: '第20条', page: 94 },
        { key: 'appendix.registration.supplementary', number: '', page: 94 },
        { key: 'appendix.registration.memberTypeNotes', number: '', page: 94 },
      ],
    },
    {
      key: 'appendix.athlete',
      number: '3',
      page: 95,
      children: [
        { key: 'appendix.athlete.purpose', number: '第1条', page: 95 },
        { key: 'appendix.athlete.definition', number: '第2条', page: 95 },
        { key: 'appendix.athlete.spirit', number: '第3条', page: 95 },
        { key: 'appendix.athlete.categories', number: '第4条', page: 95 },
        { key: 'appendix.athlete.national', number: '第5条', page: 95 },
        { key: 'appendix.athlete.general', number: '第6条', page: 95 },
        { key: 'appendix.athlete.jocContract', number: '第7条', page: 95 },
        { key: 'appendix.athlete.portrait', number: '第8条', page: 95 },
        { key: 'appendix.athlete.commercial', number: '第9条', page: 96 },
        { key: 'appendix.athlete.commercialNotice', number: '第10条', page: 96 },
        { key: 'appendix.athlete.prohibited', number: '第11条', page: 96 },
        { key: 'appendix.athlete.prizeMoney', number: '第12条', page: 96 },
        { key: 'appendix.athlete.rights', number: '第13条', page: 96 },
        { key: 'appendix.athlete.supplementary', number: '', page: 96 },
      ],
    },
    {
      key: 'appendix.antiDoping',
      number: '4',
      page: 97,
      children: [
        { key: 'appendix.antiDoping.worldCode', number: '第1条', page: 97 },
        { key: 'appendix.antiDoping.scope', number: '第2条', page: 97 },
        { key: 'appendix.antiDoping.obligations', number: '第3条', page: 98 },
        { key: 'appendix.antiDoping.mutualRecognition', number: '第4条', page: 99 },
        { key: 'appendix.antiDoping.violation', number: '第5条', page: 99 },
        { key: 'appendix.antiDoping.sanctions', number: '第6条', page: 100 },
        { key: 'appendix.antiDoping.procedure', number: '第7条', page: 100 },
        { key: 'appendix.antiDoping.notification', number: '第8条', page: 100 },
        { key: 'appendix.antiDoping.appeal', number: '第9条', page: 100 },
        { key: 'appendix.antiDoping.review', number: '第10条', page: 100 },
        { key: 'appendix.antiDoping.interpretation', number: '第11条', page: 100 },
        { key: 'appendix.antiDoping.dates', number: '', page: 100 },
      ],
    },
  ],
}
